runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

- url: /css
  static_dir: /static/css
  
- url: /js
  static_dir: /static/js
  
- url: /images
  static_dir: /static/images

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest