runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /data
  static_dir: data

- url: /static
  static_dir: static

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: numpy
  version: "1.6.1"
- name: six
  version: "1.10.0"
- name: tensorflow
  version: "1.0.1"